keys:
  - &haku_kohaku age1334dnh38zs9alhl4mjqdl307n4p07eq4frl50z0pa8c67nncaszsk9jnpz
  - &host_kohaku age1ld46fyencya7va4deayrzqcnefms68xyrxs8mv0est9aqsmakq0sxrvv2h
  - &haku_shikigami age1frzaqnc74j3858z4ja2fj5pxs7dzn9lw2vavey4fuf6jp5skks6q3pqmws
  - &host_shikigami age1hhxv99c9y4gy8r8r5adh9nlkpjruhyty975w7h0v58q3c4s0c5fsx2lphp
  - &host_yashiro age1j32v0qfvmly2w77r05uavrk4955x8jcwv30xcfxsy9dnjr8m3qeqrsft96
  - &admin age13acj7v3d6hpn70q3j4f67cx0cdtxhzstsjpvyx5gjd6cyr6n23pq3vvd4a
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *haku_kohaku
      - *host_kohaku
      - *haku_shikigami
      - *host_shikigami
      - *host_yashiro
      - *admin
