# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Kernel Module für die Hardware-Erkennung (NVMe, USB, etc.)
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # --- FILESYSTEMS REMOVED ---
  # Die Dateisysteme (/, /boot, /home) wurden entfernt, 
  # da sie nun deklarativ über 'disko.nix' verwaltet werden.
  
  # --- SWAP REMOVED ---
  # Swap wird ebenfalls entfernt. Wir nutzen zramSwap (in default.nix konfiguriert).

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
